In [17]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time 
import pandas as pd
from selenium.webdriver.support.ui import Select 
from selenium.webdriver import ActionChains

# Prob 5 Scrape the details of trending repositories on Github.com.

Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [31]:
driver= webdriver.Chrome(r"C:\Users\arkay\Downloads\chromedriver_win32 (1)\chromedriver.exe")
url='https://github.com/'
driver.get(url)
time.sleep(5)

In [32]:
r_title=[]
r_desc=[]
c_count=[]
l_used=[]

In [36]:
r_tags=driver.find_elements_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article/h1/a/span")
for i in r_tags:
    dataset=i.text
    r_title.append(dataset)
rd_tags=driver.find_elements_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article/p")
for i in rd_tags:
    dataset=i.text
    r_desc.append(dataset)
            
c_tags=driver.find_elements_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article/div[2]/a[2]")
for i in c_tags:
    dataset=i.text
    c_count.append(dataset)
l_tags=driver.find_elements_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article/div[2]/span[1]/span[2]")
for i in l_tags:
    dataset=i.text
    l_used.append(dataset)

GH=pd.DataFrame({})
GH['Repository_Name']=r_title
GH['Contributors_count']=c_count
GH['Language_Used']=l_used
GH

       Repository_Name Contributors_count     Language_Used
0            owncast /                 85                Go
1            utkusen /                 66            Python
2        DevUtilsApp /                 69       Objective-C
3         GitSquared /              1,407        JavaScript
4         FlaxEngine /                 49               C++
..                 ...                ...               ...
95          trekhleb /              2,960  Jupyter Notebook
96             ly525 /                707        JavaScript
97       storybookjs /              5,666        TypeScript
98  FirebaseExtended /              1,656              Dart
99           FreeCAD /              2,091               C++

[100 rows x 3 columns]

# Prob -7 Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [78]:
driver= webdriver.Chrome(r"C:\Users\arkay\Downloads\chromedriver_win32 (1)\chromedriver.exe")
url='https://www.naukri.com/data-science-recruiters'
driver.get(url)
time.sleep(5)
driver.maximize_window()

In [48]:
driver.find_element_by_xpath("/html/body/div[1]/div/div/ul[1]/li[2]/a").click()
time.sleep(5)

In [79]:
name=[]
des=[]
com=[]
skil=[]
loc=[]

In [80]:
n_tags=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div[1]/div[1]/p/a[1]/span")
for i in n_tags:
    dataset=i.text
    name.append(dataset)
d_tags=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div[1]/div[1]/p/span[1]")
for i in d_tags:
    dataset=i.text
    des.append(dataset)
c_tags=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div[1]/div[1]/p/a[2]")
for i in c_tags:
    dataset=i.text
    com.append(dataset)
s_tags=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div[1]/div[2]")
for i in s_tags:
    dataset=i.text
    skil.append(dataset)
l_tags=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div[1]/div[1]/p/span[2]/small")
for i in l_tags:
    dataset=i.text
    loc.append(dataset)

In [82]:
N=pd.DataFrame({})
N['Name']=name
N['Designation']=des
N['Company']=com
N['Skills_they_hire_for']=skil
N

,Name,Designation,Company,Skills_they_hire_for
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration..."
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,"Web Designing, html5, Angular.js, seo, hadoop,..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We..."
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine..."
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec..."
6,Jitendra Singh,Manager- Talent Acquisition,Compunnel Technology India Pvt. Ltd,"Python, Data Science, .Net, Java, Big Data, Da..."
7,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana..."
8,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science
9,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu..."
10,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres..."
11,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage..."
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele..."
15,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re..."
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science"
17,Rakhi,Recruitment Consultant,Walkingtext Private Limited,"Ites, Data Science, Cloud, Iot"
18,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science
19,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm..."
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee..."
23,Bharat,Lead Consultant,NEUFVASI DIGITAL SOLUTIONS PRIVATE LIMITED,"Ui Development, Product Development, Big Data,..."
24,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine..."
25,Pooja Seth,IT Technical Recruiter,RAPS iTech,"B.tech, Hr Mba, quality assurance engineering,..."
26,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc..."
27,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product..."
29,Srikanth Bellup,Director,TeachR Robotics Pvt. Ltd,"mechatronics, robotics, Home Automation, iot, ..."
30,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
31,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne..."
32,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software..."
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading..."
34,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac..."
35,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy..."
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat..."
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ..."
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private..."
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering"
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark..."
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary"
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B..."
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs"
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni..."
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute..."
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,..."
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage..."

# Prob 2 -Scrape the details team Indiaâ€™s international fixtures from bcci.tv.


Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code

In [113]:
driver= webdriver.Chrome(r"C:\Users\arkay\Downloads\chromedriver_win32 (1)\chromedriver.exe")
url='https://www.bcci.tv/international/fixtures'
driver.get(url)
time.sleep(5)
driver.maximize_window()

In [114]:
m=[]
s=[]
p=[]
d=[]
t=[]

In [115]:
m_tags=driver.find_elements_by_xpath("/html/body/div[4]/div/div/div[2]/section/div/div/a/div[2]/div[2]/p/strong")
for i in m_tags:
    dataset=i.text
    m.append(dataset)
s_tags=driver.find_elements_by_xpath("/html/body/div[4]/div/div/div[2]/section/div/div/a/div[2]/div[1]/span[2]")
for i in s_tags:
    dataset=i.text
    s.append(dataset)
p_tags=driver.find_elements_by_xpath("/html/body/div[4]/div/div/div[2]/section/div/div/a/div[2]/div[2]/p/span")
for i in p_tags:
    dataset=i.text
    p.append(dataset)
d_tags=driver.find_elements_by_xpath("/html/body/div[4]/div/div/div[2]/section/div/div/a/div[2]/div[2]/span/strong")
#d_tags=driver.find_elements_class_name("fixture__datetime tablet-only")
for i in d_tags:
    dataset=i.text
    d.append(dataset)
# /html/body/div[4]/div/div/div[2]/section/div/div/a[2]/div[2]/div[2]/span/strong
t_tags=driver.find_elements_by_class_name("fixture__local-time")
for i in t_tags:
    dataset=i.text
    t.append(dataset)

In [116]:
BCCI=pd.DataFrame({})
BCCI['Event']=m
BCCI['Series']=s
BCCI['Place']=p
BCCI['Date']=d
BCCI

,Event,Series,Place,Date
0,2nd Test,AUSTRALIA V INDIA 2020/21,"Melbourne Cricket Ground, Melbourne",
1,3rd Test,AUSTRALIA V INDIA 2020/21,"Sydney Cricket Ground, Sydney",
2,4th Test,AUSTRALIA V INDIA 2020/21,"Brisbane Cricket Ground, Brisbane",
3,1st Test,INDIA V ENGLAND 2021,"M. A. Chidambaram Stadium, Chennai",
4,2nd Test,INDIA V ENGLAND 2021,"M. A. Chidambaram Stadium, Chennai",
5,3rd Test,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
6,4th Test,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
7,1st T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
8,2nd T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
9,3rd T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
10,4th T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
11,5th T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad",
12,1st ODI,INDIA V ENGLAND 2021,"Maharashtra Cricket Association Stadium, Pune",
13,2nd ODI,INDIA V ENGLAND 2021,"Maharashtra Cricket Association Stadium, Pune",
14,3rd ODI,INDIA V ENGLAND 2021,"Maharashtra Cricket Association Stadium, Pune",
15,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",
16,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",
17,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",
18,4th Test,ENGLAND V INDIA 2021,"The Oval, London",
19,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",